### ISSUE TITLE
VISEA data is in ETRS89

### ISSUE THREAD

**Issue by bartverm** [bartverm/adcptools#1]
Latitude and Longitude coordinates collected with VISEA software are stored in ETRS89. The software currently assumes WGS84.

**Comment by iniesten** [comment]
Open Earth Tools (Deltares) contains the tool "SuperTrans". This includes data and scripts to convert between different coordinate systems: https://svn.oss.deltares.nl/repos/openearthtools/trunk/matlab/applications/SuperTrans/
